StockExchange/Controllers/AdminDashboardController.cs
using AzureServices;
using Microsoft.AspNetCore.Mvc;
using StockExchange.MiddleWare;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StockExchange.Web.Controllers
{
    public class AdminDashboardController : Controller
    {
        private readonly IUser userService;
        public AdminDashboardController(IUser userMiddleWare)
        {

        }
        public IActionResult Index()
        {
            return View();
        }


        [Route("AdminDashboardController/Tradelasthour")]
        [HttpGet]
        public IActionResult GetChartData()
        {
            var res = new StorageBlobService().Tradelasthour();

            return Json(res);
        }

        [Route("/AdminDashboardController/UsersPerPeriodChart")]
        [HttpGet]
        public IActionResult UsersPerPeriodChart()
        {
            var res = new StorageBlobService().Usersperperiod();

            return Json(res);
        }

        [Route("/AdminDashboardController/ActiveUsers")]
        [HttpGet]
        public IActionResult ActiveUsers()
        {
            var res = new StorageBlobService().ActiveUsers();

            return Json(res);
        }
        
    }
}

StockExchange/Controllers/UsersController.cs
using StockExchange.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using StockExchange.MiddleWare;

namespace StockExchange.Controllers
{
    public class UsersController : Controller
    {
        private readonly IUser userMiddleWare;
        private readonly IRole roleMiddleWare;
        private readonly UserManager<StockExchange.DataBase.Entities.User> userManager;

        public UsersController(IUser userMiddleWare, IRole roleMiddleWare, UserManager<StockExchange.DataBase.Entities.User> userManager)
        {
            this.userMiddleWare = userMiddleWare;
            this.roleMiddleWare = roleMiddleWare;
            this.userManager = userManager;
        }
        [HttpGet]
        [Authorize]
        public IActionResult EditUser(string id)
        {
            var user = userManager.GetUserAsync(HttpContext.User).Result;
            var roles = userManager.GetRolesAsync(user).Result;
            if (!roles.Contains("admin"))
            {
                return RedirectToAction("Login", "Account");
            }
            return PartialView("_EditUser", userMiddleWare.GetById(id));
        }
        [HttpPost]
        [Authorize]
        public IActionResult EditUser(EditUser user)
        {
            var currentUser = userManager.GetUserAsync(HttpContext.User).Result;
            var roles = userManager.GetRolesAsync(currentUser).Result;
            if (!roles.Contains("admin"))
            {
                return RedirectToAction("Login", "Account");
            }
            if (ModelState.IsValid)
            {
                var id = userMiddleWare.Edit(user);
                return RedirectToAction("GetAll");
            }
            else
                return PartialView("_EditUser", user);
        }
        [HttpGet]
        [Authorize]
        public IActionResult GetAll()
        {
            var currentUser = userManager.GetUserAsync(HttpContext.User).Result;
            var roles = userManager.GetRolesAsync(currentUser).Result;
            if (!roles.Contains("admin"))
            {
                return RedirectToAction("Login", "Account");
            }
            var users = userMiddleWare.GetAll();
            return View();
        }

        [HttpPost]
        [Authorize]
        public IActionResult GetUsers()
        {
            var currentUser = userManager.GetUserAsync(HttpContext.User).Result;
            var roles = userManager.GetRolesAsync(currentUser).Result;
            if (!roles.Contains("admin"))
            {
                return RedirectToAction("Login", "Account");
            }
            var length = Convert.ToInt32(Request.Form["length"]);
            var start = Convert.ToInt32(Request.Form["start"]);
            var col = Request.Form[$"columns[{Request.Form["order[0][column]"]}][name]"];
            var search = Request.Form["search[value]"];
            var dir = Request.Form["order[0][dir]"];
            var users = userMiddleWare.GetAll(col, dir, search).ToList();
            return Json(new
            {
                data = users.Skip(start).Take(length),
                recordsTotal = users.Count(),
                recordsFiltered = users.Count()
            });
        }
        [Authorize]
        public IActionResult DeleteUser(string id)
        {
            var currentUser = userManager.GetUserAsync(HttpContext.User).Result;
            var roles = userManager.GetRolesAsync(currentUser).Result;
            if (!roles.Contains("admin"))
            {
                return RedirectToAction("Login", "Account");
            }
            try
            {
                userMiddleWare.Delete(id);
            }
            catch (Exception exception)
            {
                return Json(new { status = "error" });
            }
            return RedirectToAction("GetAll");
        }

    }
}

StockExchange/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<StockExchange.DataBase.Entities.User> SignInManager
@inject UserManager<StockExchange.DataBase.Entities.User> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StocTrading</title>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
          integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

    <link href="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.css" />
    @RenderSection("Styles", required: false)

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Stock Exchange</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1 d-flex flex-row justify-content-end">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        @if (User.IsInRole("admin"))
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="GetAll">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AdminDashboard" asp-action="Index">Admin Dashboard</a>
                        </li>
                        }

                        @if (!SignInManager.IsSignedIn(User))
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                        </li>


                        }

                        @if (SignInManager.IsSignedIn(User))
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Stock" asp-action="Stocks">Stocks</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Portofolio" asp-action="Index">Portofolios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Profile">Profile</a>
                        </li>
                        <li class="nav-item">
                            <form method="post" asp-action="Logout" asp-controller="Account">
                                <button class="btn btn-light">
                                    Logout @User.Identity.Name
                                </button>
                            </form>
                        </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid" style="margin-bottom: 4rem!important;">
        <main role="main">
            @RenderBody()
            @RenderSection("Modal", required: false)
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Stock Exchange - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/js/select2.min.js"></script>

    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>